### ISSUE TITLE
Error loading CSS and JavaScript on subpages

### ISSUE THREAD

**Issue by iamchriswick** [Blockshot12/HTML-starterkit-gulp#4]
# To fix this, the following code need to be changed

## In /partials/_styles.html

Change 
`<link rel="stylesheet" href="css/style.min.css" />`
to
`<link rel="stylesheet" href="/css/style.min.css" />`

## In /partials/_scripts.html

Change
`<script src="js/scripts.min.js" type="text/javascript"></script>`
to
`<script src="/js/scripts.min.js" type="text/javascript"></script>`

**Comment by Blockshot12** [comment]
@iamchriswick Thanks for the issues comments. I fixed them all.
